export const DIS_BANNEER_LIST = 'main/DIS_BANNEER_LIST';
export const DIS_RECOMMEND_LIST = 'main/DIS_RECOMMEND_LIST';
export const EXCLUSIVED_LIST = 'main/EXCLUSIVED_LIST';
export const LATEST_MUSIC_LIST = 'main/LATEST_MUSIC_LIST';
export const LATEST_MV_LIST = 'main/LATEST_MV_LIST';
export const LIST_CLASS_IFICATION = 'main/LIST_CLASS_IFICATION';
export const THE_RECOMMENDS_SONG_LIST = 'main/THE_RECOMMENDS_SONG_LIST';
export const GET_ALEADER_BOARD = 'main/GET_ALEADER_BOARD';
